// Shared harness for runtime smokes: boots the installed Flowix DSH runtime as
// a real Cordis host with this plugin mounted, over stdio or HTTP transport.
//
// The host is `dsh-sdk-jsonrpc-demo/packaged-bin`: it boots an external Cordis
// entry-list config and never reads stdin itself (it only watches stdin EOF),
// so the plugin's stdio transport owns the process pipes. The config is
// generated by flattening the runtime's own `dsh-base` bundle patch, so the
// roster always matches the installed runtime version.
import { spawn } from 'node:child_process'
import { chmod, copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { existsSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { createInterface } from 'node:readline'
import { tmpdir } from 'node:os'

const pluginRoot = resolve(import.meta.dirname, '../..')

export function resolveRuntimeRoot(explicit = process.env.DSH_RUNTIME_ROOT) {
  if (explicit) return resolve(explicit)
  const current = join(
    process.env.HOME,
    'Library/Application Support/Flowix/dsh/current.json',
  )
  if (!existsSync(current)) {
    throw new Error(`no installed Flowix DSH found (looked at ${current}); set DSH_RUNTIME_ROOT`)
  }
  const manifest = JSON.parse(readFileSync(current, 'utf8'))
  return join(process.env.HOME, 'Library/Application Support/Flowix/dsh/versions', manifest.version)
}

/** Flatten the runtime's dsh-base bundle patch into a plain entry list. */
async function baseEntries(runtimeRoot, { realLlm = false } = {}) {
  const patchPath = join(runtimeRoot, 'runtime/node_modules/@deepseek-ai/dsh-base/cordis.patch.yml')
  const text = await readFile(patchPath, 'utf8')
  const lines = text.split('\n')
  const insertIndex = lines.findIndex(line => /^-\s*insert:\s*$/.test(line))
  if (insertIndex === -1) throw new Error(`unexpected dsh-base patch shape: ${patchPath}`)
  // Drop everything through the top-level `- insert:` row and dedent the
  // entry rows by the four spaces they are nested under it. Duplicate ids are
  // not allowed in a flat entry list, so pruned rows are disabled in place.
  // The packaged headless runtime omits the typert/api-gateway JS from its
  // closure; the flowix production profile disables the same rows.
  const pruned = new Set(['typert', 'typert-loader', 'typert-gateway', 'session-title-llm'])
  const flattened = []
  for (const line of lines.slice(insertIndex + 1)) {
    const dedented = line.startsWith('    ') ? line.slice(4) : line
    flattened.push(dedented)
    const id = /^-\s*id:\s*(\S+)\s*$/.exec(dedented)?.[1]
    if (id && pruned.has(id)) flattened.push('  disabled: true')
    // Route turns onto the user-configured pi-ai `deepseek` route instead of
    // the credential-less native adapter.
    if (realLlm && /^\s{2}provider: deepseek-official$/.test(dedented)) flattened.push(dedented.replace('deepseek-official', 'deepseek'))
  }
  return flattened.join('\n')
}

/**
 * Provision a real-model DSH home exactly the way a Flowix desktop harness
 * session does: provider routes come from the user's `~/.dsh/settings.yaml`
 * (env references only, no secrets), and the DeepSeek key is read from the
 * Flowix secret store (`~/.flowix/default.db`) into an isolated version-1
 * credentials document. The key never appears in logs or process output.
 */
async function provisionRealLlm(dshHome) {
  const userSettings = join(process.env.HOME, '.dsh/settings.yaml')
  if (!existsSync(userSettings)) throw new Error(`real-LLM smoke needs ${userSettings} (Flowix-managed DSH settings)`)
  await copyFile(userSettings, join(dshHome, 'settings.yaml'))

  const { DatabaseSync } = await import('node:sqlite')
  const secretDb = new DatabaseSync(join(process.env.HOME, '.flowix/default.db'), { readOnly: true })
  const row = secretDb.prepare("SELECT value FROM secret_kv WHERE key = 'DeepSeek::default'").get()
  secretDb.close()
  if (!row?.value) throw new Error("no DeepSeek key found in ~/.flowix/default.db (entry 'DeepSeek::default')")
  const credentialsPath = join(dshHome, '.credentials.yaml')
  await writeFile(credentialsPath, `version: 1\nrefs:\n  FLOWIX_DSH_DEEPSEEK_API_KEY: ${row.value}\n`, { mode: 0o600 })
  await chmod(credentialsPath, 0o600)
  return { credentialRef: 'FLOWIX_DSH_DEEPSEEK_API_KEY' }
}

export async function prepareRuntimeTest({ transport, realLlm = false }) {
  const runtimeRoot = resolveRuntimeRoot()
  const runRoot = await mkdtemp(join(tmpdir(), 'dsh-appserver-smoke-'))
  const dshHome = join(runRoot, 'dsh-home')
  const workspace = join(runRoot, 'workspace')
  await mkdir(dshHome)
  await mkdir(workspace)
  const llm = realLlm ? await provisionRealLlm(dshHome) : null

  const pluginConfig = transport === 'stdio'
    ? '    stdio: true'
    : `    http:\n      host: 127.0.0.1\n      port: ${transport.port}`
  // The config lives under the plugin checkout so the relative plugin name
  // resolves exactly like a bundle installed beside its config.
  const configDir = join(pluginRoot, 'test/.tmp')
  await mkdir(configDir, { recursive: true })
  const configPath = join(configDir, `cordis.appserver-${transport === 'stdio' ? 'stdio' : `http-${transport.port}`}.yml`)
  const entries = await baseEntries(runtimeRoot, { realLlm })
  const config = `${entries}

# Test harness row: the plugin under test, mounted beside the base roster.
- id: dsh-app-server
  name: '../../src/cordis-plugin.js'
  config:
${pluginConfig}
`
  await writeFile(configPath, config)

  const env = {
    ...process.env,
    DSH_HOME: dshHome,
    PATH: [join(runtimeRoot, 'bin'), join(runtimeRoot, 'node'), process.env.PATH].join(':'),
  }
  const hostBin = join(runtimeRoot, 'runtime/node_modules/@deepseek-ai/dsh-sdk-jsonrpc-demo/lib/packaged-bin.js')
  const nodeBin = join(runtimeRoot, 'node/node')

  return {
    runtimeRoot,
    runRoot,
    dshHome,
    workspace,
    configPath,
    llm,
    spawnHost() {
      const child = spawn(nodeBin, [hostBin, configPath], { cwd: workspace, env, stdio: ['pipe', 'pipe', 'pipe'] })
      child.stderr.setEncoding('utf8')
      child.stderr.on('data', chunk => { child.stderrText = (child.stderrText || '') + chunk })
      return child
    },
    async cleanup() {
      await rm(runRoot, { recursive: true, force: true })
      await rm(configPath, { force: true })
    },
  }
}

/** Line-delimited JSON-RPC client over a child's stdio. */
export class JsonlClient {
  constructor(child, { responseTimeoutMs = 20000, notificationTimeoutMs = 20000 } = {}) {
    this.child = child
    this.nextId = 1
    this.pending = new Map()
    this.notifications = []
    this.notificationWaiters = []
    this.responseTimeoutMs = responseTimeoutMs
    this.notificationTimeoutMs = notificationTimeoutMs
    this.closed = false
    this.lines = createInterface({ input: child.stdout })
    this.lines.on('line', line => {
      if (!line.trim()) return
      let message
      try { message = JSON.parse(line) } catch { return }
      if (message.method !== undefined && message.id === undefined) this.onNotification(message)
      else if (message.method !== undefined && message.id !== undefined) this.onNotification(message) // server-initiated request
      else this.onResponse(message)
    })
    this.exit = new Promise((_resolveExit, rejectExit) => {
      child.once('exit', (code, signal) => {
        this.closed = true
        rejectExit(new Error(`host exited: code=${code} signal=${signal}\n--- host stderr ---\n${child.stderrText || '(empty)'}`))
      })
    })
    // Keep the rejection surfaced even when no request is in flight.
    this.exit.catch(() => {})
  }

  /** Reject as soon as the host process dies, with captured stderr. */
  raceExit(promise) {
    return Promise.race([promise, this.exit])
  }

  onResponse(message) {
    const waiter = this.pending.get(message.id)
    if (!waiter) return
    this.pending.delete(message.id)
    waiter(message)
  }

  onNotification(message) {
    this.notifications.push(message)
    this.notificationWaiters = this.notificationWaiters.filter(waiter => {
      if (waiter.predicate(message)) { waiter.resolve(message); return false }
      return true
    })
  }

  send(rawLine) { this.child.stdin.write(`${rawLine}\n`) }

  request(method, params, { timeoutMs = this.responseTimeoutMs } = {}) {
    const id = this.nextId++
    const pending = new Promise((resolveRequest, rejectRequest) => {
      const timer = setTimeout(() => {
        this.pending.delete(id)
        rejectRequest(new Error(`response timeout: ${method} (id=${id})`))
      }, timeoutMs)
      this.pending.set(id, message => { clearTimeout(timer); resolveRequest(message) })
      this.send(JSON.stringify({ jsonrpc: '2.0', id, method, ...(params === undefined ? {} : { params }) }))
    })
    return this.raceExit(pending)
  }

  /** Respond to a server-initiated request (id + result/error, no method). */
  respondTo(id, result) {
    this.send(JSON.stringify({ jsonrpc: '2.0', id, result }))
  }

  async waitForNotification(predicate, { timeoutMs = this.notificationTimeoutMs, label = 'notification' } = {}) {
    const existing = this.notifications.find(predicate)
    if (existing) return existing
    const waiting = new Promise((resolveWait, rejectWait) => {
      const timer = setTimeout(() => {
        this.notificationWaiters = this.notificationWaiters.filter(waiter => waiter.predicate !== predicate)
        rejectWait(new Error(`notification timeout: ${label}; seen: ${this.notifications.map(n => n.method).join(', ') || 'none'}`))
      }, timeoutMs)
      const waiter = { predicate, resolve: value => { clearTimeout(timer); resolveWait(value) } }
      this.notificationWaiters.push(waiter)
    })
    return this.raceExit(waiting)
  }

  async close() {
    this.lines.close()
    if (!this.child.killed) this.child.kill('SIGTERM')
    await new Promise(resolveClose => {
      if (this.child.exitCode !== null) return resolveClose()
      const timer = setTimeout(() => { this.child.kill('SIGKILL'); resolveClose() }, 5000)
      this.child.once('exit', () => { clearTimeout(timer); resolveClose() })
    })
  }
}

export function check(label, condition, detail) {
  const status = condition ? 'PASS' : 'FAIL'
  console.log(`[${status}] ${label}${detail === undefined ? '' : ` — ${typeof detail === 'string' ? detail : JSON.stringify(detail)}`}`)
  if (!condition) process.exitCode = 1
  return condition
}
